### ISSUE TITLE
Q - play.promises: What is the main difference with Google Guava's ListenableFuture?

### ISSUE THREAD

**Issue by Zubnix** [pkriens/play#3]
I must admit I haven't fully looked into your idea, but from what I gather when reading the explanation is that it's almost identical to Guava's Listenable Future (& related operations).

**Comment by pkriens** [comment]
So?

Verstuurd vanaf mijn iPhone

Op 22 dec. 2013 om 14:46 heeft Zubnix notifications@github.com het volgende geschreven:

**Comment by Zubnix** [comment]
I think you didn't read the title...

Title: "Q - play.promises: What is the main difference with Google Guava's ListenableFuture?"

Is there a different philosophical approach to solving this problem? Is it just a hobby project to learn new things? Is it/will it be vastly superior to existing implementations (like Guava's ListenableFuture or Java 8 CompletableFuture)?

In other words.
What is the rationale to write this implementation while there are already 2 that solve the same problem?

**Comment by pkriens** [comment]
Well, if you're interested in this question then I would love to see your analysis :-)

**Comment by Zubnix** [comment]
Oh you will... ;)
